/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAiInsightsRouteImport } from './routes/app.ai-insights'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAssetsRouteImport } from './routes/app.assets'
import { Route as AppBankRouteImport } from './routes/app.bank'
import { Route as AppCatalogRouteImport } from './routes/app.catalog'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppCreditorsRouteImport } from './routes/app.creditors'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDebtorsRouteImport } from './routes/app.debtors'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppLocationsRouteImport } from './routes/app.locations'
import { Route as AppMovementsRouteImport } from './routes/app.movements'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditorsRoute = AppCreditorsRouteImport.update({
  id: '/creditors',
  path: '/creditors',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtorsRoute = AppDebtorsRouteImport.update({
  id: '/debtors',
  path: '/debtors',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsRoute = AppMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/bank': typeof AppBankRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/chat': typeof AppChatRoute
  '/app/creditors': typeof AppCreditorsRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/help': typeof AppHelpRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/bank': typeof AppBankRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/chat': typeof AppChatRoute
  '/app/creditors': typeof AppCreditorsRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/help': typeof AppHelpRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/bank': typeof AppBankRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/chat': typeof AppChatRoute
  '/app/creditors': typeof AppCreditorsRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/help': typeof AppHelpRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/ai-insights'
    | '/app/analytics'
    | '/app/assets'
    | '/app/bank'
    | '/app/catalog'
    | '/app/chat'
    | '/app/creditors'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/employees'
    | '/app/expenses'
    | '/app/help'
    | '/app/locations'
    | '/app/movements'
    | '/app/orders'
    | '/app/reports'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/ai-insights'
    | '/app/analytics'
    | '/app/assets'
    | '/app/bank'
    | '/app/catalog'
    | '/app/chat'
    | '/app/creditors'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/employees'
    | '/app/expenses'
    | '/app/help'
    | '/app/locations'
    | '/app/movements'
    | '/app/orders'
    | '/app/reports'
    | '/app/settings'
    | '/app/suppliers'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/ai-insights'
    | '/app/analytics'
    | '/app/assets'
    | '/app/bank'
    | '/app/catalog'
    | '/app/chat'
    | '/app/creditors'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/employees'
    | '/app/expenses'
    | '/app/help'
    | '/app/locations'
    | '/app/movements'
    | '/app/orders'
    | '/app/reports'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-insights': {
      id: '/app/ai-insights'
      path: '/ai-insights'
      fullPath: '/app/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bank': {
      id: '/app/bank'
      path: '/bank'
      fullPath: '/app/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/creditors': {
      id: '/app/creditors'
      path: '/creditors'
      fullPath: '/app/creditors'
      preLoaderRoute: typeof AppCreditorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debtors': {
      id: '/app/debtors'
      path: '/debtors'
      fullPath: '/app/debtors'
      preLoaderRoute: typeof AppDebtorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations': {
      id: '/app/locations'
      path: '/locations'
      fullPath: '/app/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/movements': {
      id: '/app/movements'
      path: '/movements'
      fullPath: '/app/movements'
      preLoaderRoute: typeof AppMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppBankRoute: typeof AppBankRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppChatRoute: typeof AppChatRoute
  AppCreditorsRoute: typeof AppCreditorsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebtorsRoute: typeof AppDebtorsRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppHelpRoute: typeof AppHelpRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppMovementsRoute: typeof AppMovementsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppBankRoute: AppBankRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppChatRoute: AppChatRoute,
  AppCreditorsRoute: AppCreditorsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebtorsRoute: AppDebtorsRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppHelpRoute: AppHelpRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppMovementsRoute: AppMovementsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
